# Generated by Django 5.1.2 on 2024-11-06 09:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agrostore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('status', models.CharField(choices=[('not approved', 'Not approved'), ('pending', 'Pending'), ('complete', 'Complete')], default=True, max_length=150)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agrostore.saleitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
