# Generated by Django 5.1.2 on 2024-11-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agrostore', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
