# Generated by Django 5.1.2 on 2024-11-25 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agrostore', '0005_task_description_task_due_date_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sale_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agrostore.saleitem'),
        ),
    ]
